apiVersion: apps/v1
kind: Deployment
metadata:
  name: elsa
  labels:
    app: elsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elsa
  template:
    metadata:
      labels:
        app: elsa
    spec:
      containers:
        - name: elsa
          image: registry.blechschmidt.de/elsa:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: elsa
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: elsa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elsa
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - elsa.blechschmidt.dev
      secretName: elsa-tls
  rules:
    - host: elsa.blechschmidt.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elsa
                port:
                  number: 80
