[package]
name = "path-finding"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = "0.31"
geo = "0.18"

image = "0.23"
imageproc = "0.22"
rusttype = "0.9"