[package]
name = "height-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proj = "0.24.0"
serde_yaml = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
geo = "0.18.0"